name: deployment to prod
on:
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - uses: actions/checkout@v4
    - run: echo "secret is ${{ secrets.MY_SECRET }}"
    - run: echo "variable is ${{ vars.MY_VARIABLE }}"
    - uses: ./secure-gha
