name: other workflow
on:
  pull_request:
    branches: [main]
  workflow_dispatch: {}

jobs:
  verify-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/workflows/verify-pr.yaml@main

  build:
    needs: verify-pr
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - uses: actions/checkout@v4
    - run: echo "secret is ${{ secrets.MY_SECRET }}"
    - run: echo "variable is ${{ vars.MY_VARIABLE }}"
