name: Check PR Prequisites
on:
  workflow_call: 

permissions:
  pull-requests: write
  contents: read
  repository-projects: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - uses: ./secure-gha/
    - run: printenv

