name: Check PR Prequisites
on:
  pull_request_target: 
    branches: [main]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - uses: ./secure-gha/
    - run: printenv
    - run: gh pr edit --repo --add-label ok-to-test

