name: verify-pr
on:
  pull_request:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run:
        gh pr diff 1 -R rajatjindal/secure-gha --name-only > changed-files.txt
        for forbidden_file in $(cat config/forbidden-files.txt); do;
          if [[ $(grep $forbidden_file changed-files.txt) ]]; then
            echo "forbidden file $forbidden_file changed"
          fi
        done;

        ##for id in $(gh run list -b check-pr -R rajatjindal/secure-gha --json databaseId | jq '.[].databaseId'); do gh run cancel $id; done;    
      env:
        GH_TOKEN: ${{ github.token }}