name: verify-pr
on:
  pull_request:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run:
        for file in $(gh pr diff 1 -R rajatjindal/secure-gha --name-only); do
          echo "$file";
        done;

        ##for id in $(gh run list -b check-pr -R rajatjindal/secure-gha --json databaseId | jq '.[].databaseId'); do gh run cancel $id; done;    