name: other workflow
on:
  pull_request:
    branches: [main]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v4
    - run: echo "i am other workflow"
    - run: echo "secret is ${{ secrets.MY_SECRET }}"
    - run: echo "variable is ${{ vars.MY_VARIABLE }}"
